version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies :arrow_up_small:'
      - 'github_actions'
      - 'x:size/small'

  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies :arrow_up_small:'
      - 'javascript'
      - 'x:size/small'