[canonical-tests]

# empty strands
"f6dcb64f-03b0-4b60-81b1-3c9dbf47e887" = true

# single letter identical strands
"54681314-eee2-439a-9db0-b0636c656156" = true

# single letter different strands
"294479a3-a4c8-478f-8d63-6209815a827b" = true

# long identical strands
"9aed5f34-5693-4344-9b31-40c692fb5592" = true

# long different strands
"cd2273a5-c576-46c8-a52b-dee251c3e6e5" = true

# disallow first strand longer
"919f8ef0-b767-4d1b-8516-6379d07fcb28" = false

# disallow first strand longer
"b9228bb1-465f-4141-b40f-1f99812de5a8" = true

# disallow second strand longer
"8a2d4ed0-ead5-4fdd-924d-27c4cf56e60e" = false

# disallow second strand longer
"dab38838-26bb-4fff-acbe-3b0a9bfeba2d" = true

# disallow left empty strand
"5dce058b-28d4-4ca7-aa64-adfe4e17784c" = false

# disallow left empty strand
"db92e77e-7c72-499d-8fe6-9354d2bfd504" = false

# disallow empty first strand
"b764d47c-83ff-4de2-ab10-6cfe4b15c0f3" = true

# disallow right empty strand
"38826d4b-16fb-4639-ac3e-ba027dec8b5f" = false

# disallow right empty strand
"920cd6e3-18f4-4143-b6b8-74270bb8f8a3" = false

# disallow empty second strand
"9ab9262f-3521-4191-81f5-0ed184a5aa89" = true
