# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: javascript / pr

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Use Node.js LTS (14.x)
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # v2.1.5
        with:
          node-version: 14.x

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci precheck (stub files, config integrity) for changed exercises
        run: |
          PULL_REQUEST_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          curl --url $"${PULL_REQUEST_URL}/files?per_page=100" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
            jq -c '.[] | select(.status == "added" or .status == "modified") | select(.filename | match("\\.(js|jsx|md|json)$")) | .filename' | \
            xargs -r npx babel-node scripts/pr-check

  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]

    steps:
      - name: Checkout PR
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci (runs tests) for changed/added exercises
        run: |
          PULL_REQUEST_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          curl --url $"${PULL_REQUEST_URL}/files?per_page=100" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
            jq -c '.[] | select(.status == "added" or .status == "modified") | select(.filename | match("\\.(js|jsx|md|json)$")) | .filename' | \
            xargs -r npx babel-node scripts/pr
