# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: javascript / pr

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: '16'

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci precheck (stub files, config integrity) for changed exercises
        run: |
          PULL_REQUEST_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          curl --url $"${PULL_REQUEST_URL}/files?per_page=100" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
            jq -c '.[] | select(.status == "added" or .status == "modified") | select(.filename | match("\\.(js|jsx|md|json)$")) | .filename' | \
            xargs -r npx babel-node scripts/pr-check
          bin/check_corejs_version.sh

  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16', '17']

    steps:
      - name: Checkout PR
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci (runs tests) for changed/added exercises
        run: |
          PULL_REQUEST_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          curl --url $"${PULL_REQUEST_URL}/files?per_page=100" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
            jq -c '.[] | select(.status == "added" or .status == "modified") | select(.filename | match("\\.(js|jsx|md|json)$")) | .filename' | \
            xargs -r npx babel-node scripts/pr
